// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package integrationjira

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-gitlab.integrationJira.IntegrationJira",
		reflect.TypeOf((*IntegrationJira)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "active", GoGetter: "Active"},
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "apiUrl", GoGetter: "ApiUrl"},
			_jsii_.MemberProperty{JsiiProperty: "apiUrlInput", GoGetter: "ApiUrlInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "commentOnEventEnabled", GoGetter: "CommentOnEventEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "commentOnEventEnabledInput", GoGetter: "CommentOnEventEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "commitEvents", GoGetter: "CommitEvents"},
			_jsii_.MemberProperty{JsiiProperty: "commitEventsInput", GoGetter: "CommitEventsInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "createdAt", GoGetter: "CreatedAt"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "issuesEnabled", GoGetter: "IssuesEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "issuesEnabledInput", GoGetter: "IssuesEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "jiraAuthType", GoGetter: "JiraAuthType"},
			_jsii_.MemberProperty{JsiiProperty: "jiraAuthTypeInput", GoGetter: "JiraAuthTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "jiraIssuePrefix", GoGetter: "JiraIssuePrefix"},
			_jsii_.MemberProperty{JsiiProperty: "jiraIssuePrefixInput", GoGetter: "JiraIssuePrefixInput"},
			_jsii_.MemberProperty{JsiiProperty: "jiraIssueRegex", GoGetter: "JiraIssueRegex"},
			_jsii_.MemberProperty{JsiiProperty: "jiraIssueRegexInput", GoGetter: "JiraIssueRegexInput"},
			_jsii_.MemberProperty{JsiiProperty: "jiraIssueTransitionAutomatic", GoGetter: "JiraIssueTransitionAutomatic"},
			_jsii_.MemberProperty{JsiiProperty: "jiraIssueTransitionAutomaticInput", GoGetter: "JiraIssueTransitionAutomaticInput"},
			_jsii_.MemberProperty{JsiiProperty: "jiraIssueTransitionId", GoGetter: "JiraIssueTransitionId"},
			_jsii_.MemberProperty{JsiiProperty: "jiraIssueTransitionIdInput", GoGetter: "JiraIssueTransitionIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "mergeRequestsEvents", GoGetter: "MergeRequestsEvents"},
			_jsii_.MemberProperty{JsiiProperty: "mergeRequestsEventsInput", GoGetter: "MergeRequestsEventsInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "password", GoGetter: "Password"},
			_jsii_.MemberProperty{JsiiProperty: "passwordInput", GoGetter: "PasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "project", GoGetter: "Project"},
			_jsii_.MemberProperty{JsiiProperty: "projectInput", GoGetter: "ProjectInput"},
			_jsii_.MemberProperty{JsiiProperty: "projectKey", GoGetter: "ProjectKey"},
			_jsii_.MemberProperty{JsiiProperty: "projectKeyInput", GoGetter: "ProjectKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "projectKeys", GoGetter: "ProjectKeys"},
			_jsii_.MemberProperty{JsiiProperty: "projectKeysInput", GoGetter: "ProjectKeysInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetApiUrl", GoMethod: "ResetApiUrl"},
			_jsii_.MemberMethod{JsiiMethod: "resetCommentOnEventEnabled", GoMethod: "ResetCommentOnEventEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetCommitEvents", GoMethod: "ResetCommitEvents"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetIssuesEnabled", GoMethod: "ResetIssuesEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetJiraAuthType", GoMethod: "ResetJiraAuthType"},
			_jsii_.MemberMethod{JsiiMethod: "resetJiraIssuePrefix", GoMethod: "ResetJiraIssuePrefix"},
			_jsii_.MemberMethod{JsiiMethod: "resetJiraIssueRegex", GoMethod: "ResetJiraIssueRegex"},
			_jsii_.MemberMethod{JsiiMethod: "resetJiraIssueTransitionAutomatic", GoMethod: "ResetJiraIssueTransitionAutomatic"},
			_jsii_.MemberMethod{JsiiMethod: "resetJiraIssueTransitionId", GoMethod: "ResetJiraIssueTransitionId"},
			_jsii_.MemberMethod{JsiiMethod: "resetMergeRequestsEvents", GoMethod: "ResetMergeRequestsEvents"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetProjectKey", GoMethod: "ResetProjectKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetProjectKeys", GoMethod: "ResetProjectKeys"},
			_jsii_.MemberMethod{JsiiMethod: "resetUseInheritedSettings", GoMethod: "ResetUseInheritedSettings"},
			_jsii_.MemberMethod{JsiiMethod: "resetUsername", GoMethod: "ResetUsername"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "title", GoGetter: "Title"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "updatedAt", GoGetter: "UpdatedAt"},
			_jsii_.MemberProperty{JsiiProperty: "url", GoGetter: "Url"},
			_jsii_.MemberProperty{JsiiProperty: "urlInput", GoGetter: "UrlInput"},
			_jsii_.MemberProperty{JsiiProperty: "useInheritedSettings", GoGetter: "UseInheritedSettings"},
			_jsii_.MemberProperty{JsiiProperty: "useInheritedSettingsInput", GoGetter: "UseInheritedSettingsInput"},
			_jsii_.MemberProperty{JsiiProperty: "username", GoGetter: "Username"},
			_jsii_.MemberProperty{JsiiProperty: "usernameInput", GoGetter: "UsernameInput"},
		},
		func() interface{} {
			j := jsiiProxy_IntegrationJira{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-gitlab.integrationJira.IntegrationJiraConfig",
		reflect.TypeOf((*IntegrationJiraConfig)(nil)).Elem(),
	)
}
