package project

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-gitlab.project.Project",
		reflect.TypeOf((*Project)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "allowMergeOnSkippedPipeline", GoGetter: "AllowMergeOnSkippedPipeline"},
			_jsii_.MemberProperty{JsiiProperty: "allowMergeOnSkippedPipelineInput", GoGetter: "AllowMergeOnSkippedPipelineInput"},
			_jsii_.MemberProperty{JsiiProperty: "analyticsAccessLevel", GoGetter: "AnalyticsAccessLevel"},
			_jsii_.MemberProperty{JsiiProperty: "analyticsAccessLevelInput", GoGetter: "AnalyticsAccessLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "approvalsBeforeMerge", GoGetter: "ApprovalsBeforeMerge"},
			_jsii_.MemberProperty{JsiiProperty: "approvalsBeforeMergeInput", GoGetter: "ApprovalsBeforeMergeInput"},
			_jsii_.MemberProperty{JsiiProperty: "archived", GoGetter: "Archived"},
			_jsii_.MemberProperty{JsiiProperty: "archivedInput", GoGetter: "ArchivedInput"},
			_jsii_.MemberProperty{JsiiProperty: "archiveOnDestroy", GoGetter: "ArchiveOnDestroy"},
			_jsii_.MemberProperty{JsiiProperty: "archiveOnDestroyInput", GoGetter: "ArchiveOnDestroyInput"},
			_jsii_.MemberProperty{JsiiProperty: "autoCancelPendingPipelines", GoGetter: "AutoCancelPendingPipelines"},
			_jsii_.MemberProperty{JsiiProperty: "autoCancelPendingPipelinesInput", GoGetter: "AutoCancelPendingPipelinesInput"},
			_jsii_.MemberProperty{JsiiProperty: "autocloseReferencedIssues", GoGetter: "AutocloseReferencedIssues"},
			_jsii_.MemberProperty{JsiiProperty: "autocloseReferencedIssuesInput", GoGetter: "AutocloseReferencedIssuesInput"},
			_jsii_.MemberProperty{JsiiProperty: "autoDevopsDeployStrategy", GoGetter: "AutoDevopsDeployStrategy"},
			_jsii_.MemberProperty{JsiiProperty: "autoDevopsDeployStrategyInput", GoGetter: "AutoDevopsDeployStrategyInput"},
			_jsii_.MemberProperty{JsiiProperty: "autoDevopsEnabled", GoGetter: "AutoDevopsEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "autoDevopsEnabledInput", GoGetter: "AutoDevopsEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "avatar", GoGetter: "Avatar"},
			_jsii_.MemberProperty{JsiiProperty: "avatarHash", GoGetter: "AvatarHash"},
			_jsii_.MemberProperty{JsiiProperty: "avatarHashInput", GoGetter: "AvatarHashInput"},
			_jsii_.MemberProperty{JsiiProperty: "avatarInput", GoGetter: "AvatarInput"},
			_jsii_.MemberProperty{JsiiProperty: "avatarUrl", GoGetter: "AvatarUrl"},
			_jsii_.MemberProperty{JsiiProperty: "buildCoverageRegex", GoGetter: "BuildCoverageRegex"},
			_jsii_.MemberProperty{JsiiProperty: "buildCoverageRegexInput", GoGetter: "BuildCoverageRegexInput"},
			_jsii_.MemberProperty{JsiiProperty: "buildGitStrategy", GoGetter: "BuildGitStrategy"},
			_jsii_.MemberProperty{JsiiProperty: "buildGitStrategyInput", GoGetter: "BuildGitStrategyInput"},
			_jsii_.MemberProperty{JsiiProperty: "buildsAccessLevel", GoGetter: "BuildsAccessLevel"},
			_jsii_.MemberProperty{JsiiProperty: "buildsAccessLevelInput", GoGetter: "BuildsAccessLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "buildTimeout", GoGetter: "BuildTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "buildTimeoutInput", GoGetter: "BuildTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "ciConfigPath", GoGetter: "CiConfigPath"},
			_jsii_.MemberProperty{JsiiProperty: "ciConfigPathInput", GoGetter: "CiConfigPathInput"},
			_jsii_.MemberProperty{JsiiProperty: "ciDefaultGitDepth", GoGetter: "CiDefaultGitDepth"},
			_jsii_.MemberProperty{JsiiProperty: "ciDefaultGitDepthInput", GoGetter: "CiDefaultGitDepthInput"},
			_jsii_.MemberProperty{JsiiProperty: "ciForwardDeploymentEnabled", GoGetter: "CiForwardDeploymentEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "ciForwardDeploymentEnabledInput", GoGetter: "CiForwardDeploymentEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "ciSeparatedCaches", GoGetter: "CiSeparatedCaches"},
			_jsii_.MemberProperty{JsiiProperty: "ciSeparatedCachesInput", GoGetter: "CiSeparatedCachesInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "containerExpirationPolicy", GoGetter: "ContainerExpirationPolicy"},
			_jsii_.MemberProperty{JsiiProperty: "containerExpirationPolicyInput", GoGetter: "ContainerExpirationPolicyInput"},
			_jsii_.MemberProperty{JsiiProperty: "containerRegistryAccessLevel", GoGetter: "ContainerRegistryAccessLevel"},
			_jsii_.MemberProperty{JsiiProperty: "containerRegistryAccessLevelInput", GoGetter: "ContainerRegistryAccessLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "containerRegistryEnabled", GoGetter: "ContainerRegistryEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "containerRegistryEnabledInput", GoGetter: "ContainerRegistryEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "defaultBranch", GoGetter: "DefaultBranch"},
			_jsii_.MemberProperty{JsiiProperty: "defaultBranchInput", GoGetter: "DefaultBranchInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "description", GoGetter: "Description"},
			_jsii_.MemberProperty{JsiiProperty: "descriptionInput", GoGetter: "DescriptionInput"},
			_jsii_.MemberProperty{JsiiProperty: "emailsDisabled", GoGetter: "EmailsDisabled"},
			_jsii_.MemberProperty{JsiiProperty: "emailsDisabledInput", GoGetter: "EmailsDisabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "externalAuthorizationClassificationLabel", GoGetter: "ExternalAuthorizationClassificationLabel"},
			_jsii_.MemberProperty{JsiiProperty: "externalAuthorizationClassificationLabelInput", GoGetter: "ExternalAuthorizationClassificationLabelInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "forkedFromProjectId", GoGetter: "ForkedFromProjectId"},
			_jsii_.MemberProperty{JsiiProperty: "forkedFromProjectIdInput", GoGetter: "ForkedFromProjectIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "forkingAccessLevel", GoGetter: "ForkingAccessLevel"},
			_jsii_.MemberProperty{JsiiProperty: "forkingAccessLevelInput", GoGetter: "ForkingAccessLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "groupWithProjectTemplatesId", GoGetter: "GroupWithProjectTemplatesId"},
			_jsii_.MemberProperty{JsiiProperty: "groupWithProjectTemplatesIdInput", GoGetter: "GroupWithProjectTemplatesIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "httpUrlToRepo", GoGetter: "HttpUrlToRepo"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberProperty{JsiiProperty: "importUrl", GoGetter: "ImportUrl"},
			_jsii_.MemberProperty{JsiiProperty: "importUrlInput", GoGetter: "ImportUrlInput"},
			_jsii_.MemberProperty{JsiiProperty: "importUrlPassword", GoGetter: "ImportUrlPassword"},
			_jsii_.MemberProperty{JsiiProperty: "importUrlPasswordInput", GoGetter: "ImportUrlPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "importUrlUsername", GoGetter: "ImportUrlUsername"},
			_jsii_.MemberProperty{JsiiProperty: "importUrlUsernameInput", GoGetter: "ImportUrlUsernameInput"},
			_jsii_.MemberProperty{JsiiProperty: "initializeWithReadme", GoGetter: "InitializeWithReadme"},
			_jsii_.MemberProperty{JsiiProperty: "initializeWithReadmeInput", GoGetter: "InitializeWithReadmeInput"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "issuesAccessLevel", GoGetter: "IssuesAccessLevel"},
			_jsii_.MemberProperty{JsiiProperty: "issuesAccessLevelInput", GoGetter: "IssuesAccessLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "issuesEnabled", GoGetter: "IssuesEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "issuesEnabledInput", GoGetter: "IssuesEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "issuesTemplate", GoGetter: "IssuesTemplate"},
			_jsii_.MemberProperty{JsiiProperty: "issuesTemplateInput", GoGetter: "IssuesTemplateInput"},
			_jsii_.MemberProperty{JsiiProperty: "lfsEnabled", GoGetter: "LfsEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "lfsEnabledInput", GoGetter: "LfsEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "mergeCommitTemplate", GoGetter: "MergeCommitTemplate"},
			_jsii_.MemberProperty{JsiiProperty: "mergeCommitTemplateInput", GoGetter: "MergeCommitTemplateInput"},
			_jsii_.MemberProperty{JsiiProperty: "mergeMethod", GoGetter: "MergeMethod"},
			_jsii_.MemberProperty{JsiiProperty: "mergeMethodInput", GoGetter: "MergeMethodInput"},
			_jsii_.MemberProperty{JsiiProperty: "mergePipelinesEnabled", GoGetter: "MergePipelinesEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "mergePipelinesEnabledInput", GoGetter: "MergePipelinesEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "mergeRequestsAccessLevel", GoGetter: "MergeRequestsAccessLevel"},
			_jsii_.MemberProperty{JsiiProperty: "mergeRequestsAccessLevelInput", GoGetter: "MergeRequestsAccessLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "mergeRequestsEnabled", GoGetter: "MergeRequestsEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "mergeRequestsEnabledInput", GoGetter: "MergeRequestsEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "mergeRequestsTemplate", GoGetter: "MergeRequestsTemplate"},
			_jsii_.MemberProperty{JsiiProperty: "mergeRequestsTemplateInput", GoGetter: "MergeRequestsTemplateInput"},
			_jsii_.MemberProperty{JsiiProperty: "mergeTrainsEnabled", GoGetter: "MergeTrainsEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "mergeTrainsEnabledInput", GoGetter: "MergeTrainsEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "mirror", GoGetter: "Mirror"},
			_jsii_.MemberProperty{JsiiProperty: "mirrorInput", GoGetter: "MirrorInput"},
			_jsii_.MemberProperty{JsiiProperty: "mirrorOverwritesDivergedBranches", GoGetter: "MirrorOverwritesDivergedBranches"},
			_jsii_.MemberProperty{JsiiProperty: "mirrorOverwritesDivergedBranchesInput", GoGetter: "MirrorOverwritesDivergedBranchesInput"},
			_jsii_.MemberProperty{JsiiProperty: "mirrorTriggerBuilds", GoGetter: "MirrorTriggerBuilds"},
			_jsii_.MemberProperty{JsiiProperty: "mirrorTriggerBuildsInput", GoGetter: "MirrorTriggerBuildsInput"},
			_jsii_.MemberProperty{JsiiProperty: "mrDefaultTargetSelf", GoGetter: "MrDefaultTargetSelf"},
			_jsii_.MemberProperty{JsiiProperty: "mrDefaultTargetSelfInput", GoGetter: "MrDefaultTargetSelfInput"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "namespaceId", GoGetter: "NamespaceId"},
			_jsii_.MemberProperty{JsiiProperty: "namespaceIdInput", GoGetter: "NamespaceIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "onlyAllowMergeIfAllDiscussionsAreResolved", GoGetter: "OnlyAllowMergeIfAllDiscussionsAreResolved"},
			_jsii_.MemberProperty{JsiiProperty: "onlyAllowMergeIfAllDiscussionsAreResolvedInput", GoGetter: "OnlyAllowMergeIfAllDiscussionsAreResolvedInput"},
			_jsii_.MemberProperty{JsiiProperty: "onlyAllowMergeIfPipelineSucceeds", GoGetter: "OnlyAllowMergeIfPipelineSucceeds"},
			_jsii_.MemberProperty{JsiiProperty: "onlyAllowMergeIfPipelineSucceedsInput", GoGetter: "OnlyAllowMergeIfPipelineSucceedsInput"},
			_jsii_.MemberProperty{JsiiProperty: "onlyMirrorProtectedBranches", GoGetter: "OnlyMirrorProtectedBranches"},
			_jsii_.MemberProperty{JsiiProperty: "onlyMirrorProtectedBranchesInput", GoGetter: "OnlyMirrorProtectedBranchesInput"},
			_jsii_.MemberProperty{JsiiProperty: "operationsAccessLevel", GoGetter: "OperationsAccessLevel"},
			_jsii_.MemberProperty{JsiiProperty: "operationsAccessLevelInput", GoGetter: "OperationsAccessLevelInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "packagesEnabled", GoGetter: "PackagesEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "packagesEnabledInput", GoGetter: "PackagesEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "pagesAccessLevel", GoGetter: "PagesAccessLevel"},
			_jsii_.MemberProperty{JsiiProperty: "pagesAccessLevelInput", GoGetter: "PagesAccessLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "path", GoGetter: "Path"},
			_jsii_.MemberProperty{JsiiProperty: "pathInput", GoGetter: "PathInput"},
			_jsii_.MemberProperty{JsiiProperty: "pathWithNamespace", GoGetter: "PathWithNamespace"},
			_jsii_.MemberProperty{JsiiProperty: "pipelinesEnabled", GoGetter: "PipelinesEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "pipelinesEnabledInput", GoGetter: "PipelinesEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "printingMergeRequestLinkEnabled", GoGetter: "PrintingMergeRequestLinkEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "printingMergeRequestLinkEnabledInput", GoGetter: "PrintingMergeRequestLinkEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "publicBuilds", GoGetter: "PublicBuilds"},
			_jsii_.MemberProperty{JsiiProperty: "publicBuildsInput", GoGetter: "PublicBuildsInput"},
			_jsii_.MemberProperty{JsiiProperty: "pushRules", GoGetter: "PushRules"},
			_jsii_.MemberProperty{JsiiProperty: "pushRulesInput", GoGetter: "PushRulesInput"},
			_jsii_.MemberMethod{JsiiMethod: "putContainerExpirationPolicy", GoMethod: "PutContainerExpirationPolicy"},
			_jsii_.MemberMethod{JsiiMethod: "putPushRules", GoMethod: "PutPushRules"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "removeSourceBranchAfterMerge", GoGetter: "RemoveSourceBranchAfterMerge"},
			_jsii_.MemberProperty{JsiiProperty: "removeSourceBranchAfterMergeInput", GoGetter: "RemoveSourceBranchAfterMergeInput"},
			_jsii_.MemberProperty{JsiiProperty: "repositoryAccessLevel", GoGetter: "RepositoryAccessLevel"},
			_jsii_.MemberProperty{JsiiProperty: "repositoryAccessLevelInput", GoGetter: "RepositoryAccessLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "repositoryStorage", GoGetter: "RepositoryStorage"},
			_jsii_.MemberProperty{JsiiProperty: "repositoryStorageInput", GoGetter: "RepositoryStorageInput"},
			_jsii_.MemberProperty{JsiiProperty: "requestAccessEnabled", GoGetter: "RequestAccessEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "requestAccessEnabledInput", GoGetter: "RequestAccessEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "requirementsAccessLevel", GoGetter: "RequirementsAccessLevel"},
			_jsii_.MemberProperty{JsiiProperty: "requirementsAccessLevelInput", GoGetter: "RequirementsAccessLevelInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowMergeOnSkippedPipeline", GoMethod: "ResetAllowMergeOnSkippedPipeline"},
			_jsii_.MemberMethod{JsiiMethod: "resetAnalyticsAccessLevel", GoMethod: "ResetAnalyticsAccessLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetApprovalsBeforeMerge", GoMethod: "ResetApprovalsBeforeMerge"},
			_jsii_.MemberMethod{JsiiMethod: "resetArchived", GoMethod: "ResetArchived"},
			_jsii_.MemberMethod{JsiiMethod: "resetArchiveOnDestroy", GoMethod: "ResetArchiveOnDestroy"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutoCancelPendingPipelines", GoMethod: "ResetAutoCancelPendingPipelines"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutocloseReferencedIssues", GoMethod: "ResetAutocloseReferencedIssues"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutoDevopsDeployStrategy", GoMethod: "ResetAutoDevopsDeployStrategy"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutoDevopsEnabled", GoMethod: "ResetAutoDevopsEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetAvatar", GoMethod: "ResetAvatar"},
			_jsii_.MemberMethod{JsiiMethod: "resetAvatarHash", GoMethod: "ResetAvatarHash"},
			_jsii_.MemberMethod{JsiiMethod: "resetBuildCoverageRegex", GoMethod: "ResetBuildCoverageRegex"},
			_jsii_.MemberMethod{JsiiMethod: "resetBuildGitStrategy", GoMethod: "ResetBuildGitStrategy"},
			_jsii_.MemberMethod{JsiiMethod: "resetBuildsAccessLevel", GoMethod: "ResetBuildsAccessLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetBuildTimeout", GoMethod: "ResetBuildTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetCiConfigPath", GoMethod: "ResetCiConfigPath"},
			_jsii_.MemberMethod{JsiiMethod: "resetCiDefaultGitDepth", GoMethod: "ResetCiDefaultGitDepth"},
			_jsii_.MemberMethod{JsiiMethod: "resetCiForwardDeploymentEnabled", GoMethod: "ResetCiForwardDeploymentEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetCiSeparatedCaches", GoMethod: "ResetCiSeparatedCaches"},
			_jsii_.MemberMethod{JsiiMethod: "resetContainerExpirationPolicy", GoMethod: "ResetContainerExpirationPolicy"},
			_jsii_.MemberMethod{JsiiMethod: "resetContainerRegistryAccessLevel", GoMethod: "ResetContainerRegistryAccessLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetContainerRegistryEnabled", GoMethod: "ResetContainerRegistryEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetDefaultBranch", GoMethod: "ResetDefaultBranch"},
			_jsii_.MemberMethod{JsiiMethod: "resetDescription", GoMethod: "ResetDescription"},
			_jsii_.MemberMethod{JsiiMethod: "resetEmailsDisabled", GoMethod: "ResetEmailsDisabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetExternalAuthorizationClassificationLabel", GoMethod: "ResetExternalAuthorizationClassificationLabel"},
			_jsii_.MemberMethod{JsiiMethod: "resetForkedFromProjectId", GoMethod: "ResetForkedFromProjectId"},
			_jsii_.MemberMethod{JsiiMethod: "resetForkingAccessLevel", GoMethod: "ResetForkingAccessLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetGroupWithProjectTemplatesId", GoMethod: "ResetGroupWithProjectTemplatesId"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetImportUrl", GoMethod: "ResetImportUrl"},
			_jsii_.MemberMethod{JsiiMethod: "resetImportUrlPassword", GoMethod: "ResetImportUrlPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetImportUrlUsername", GoMethod: "ResetImportUrlUsername"},
			_jsii_.MemberMethod{JsiiMethod: "resetInitializeWithReadme", GoMethod: "ResetInitializeWithReadme"},
			_jsii_.MemberMethod{JsiiMethod: "resetIssuesAccessLevel", GoMethod: "ResetIssuesAccessLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetIssuesEnabled", GoMethod: "ResetIssuesEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetIssuesTemplate", GoMethod: "ResetIssuesTemplate"},
			_jsii_.MemberMethod{JsiiMethod: "resetLfsEnabled", GoMethod: "ResetLfsEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetMergeCommitTemplate", GoMethod: "ResetMergeCommitTemplate"},
			_jsii_.MemberMethod{JsiiMethod: "resetMergeMethod", GoMethod: "ResetMergeMethod"},
			_jsii_.MemberMethod{JsiiMethod: "resetMergePipelinesEnabled", GoMethod: "ResetMergePipelinesEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetMergeRequestsAccessLevel", GoMethod: "ResetMergeRequestsAccessLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetMergeRequestsEnabled", GoMethod: "ResetMergeRequestsEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetMergeRequestsTemplate", GoMethod: "ResetMergeRequestsTemplate"},
			_jsii_.MemberMethod{JsiiMethod: "resetMergeTrainsEnabled", GoMethod: "ResetMergeTrainsEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetMirror", GoMethod: "ResetMirror"},
			_jsii_.MemberMethod{JsiiMethod: "resetMirrorOverwritesDivergedBranches", GoMethod: "ResetMirrorOverwritesDivergedBranches"},
			_jsii_.MemberMethod{JsiiMethod: "resetMirrorTriggerBuilds", GoMethod: "ResetMirrorTriggerBuilds"},
			_jsii_.MemberMethod{JsiiMethod: "resetMrDefaultTargetSelf", GoMethod: "ResetMrDefaultTargetSelf"},
			_jsii_.MemberMethod{JsiiMethod: "resetNamespaceId", GoMethod: "ResetNamespaceId"},
			_jsii_.MemberMethod{JsiiMethod: "resetOnlyAllowMergeIfAllDiscussionsAreResolved", GoMethod: "ResetOnlyAllowMergeIfAllDiscussionsAreResolved"},
			_jsii_.MemberMethod{JsiiMethod: "resetOnlyAllowMergeIfPipelineSucceeds", GoMethod: "ResetOnlyAllowMergeIfPipelineSucceeds"},
			_jsii_.MemberMethod{JsiiMethod: "resetOnlyMirrorProtectedBranches", GoMethod: "ResetOnlyMirrorProtectedBranches"},
			_jsii_.MemberMethod{JsiiMethod: "resetOperationsAccessLevel", GoMethod: "ResetOperationsAccessLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPackagesEnabled", GoMethod: "ResetPackagesEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetPagesAccessLevel", GoMethod: "ResetPagesAccessLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetPath", GoMethod: "ResetPath"},
			_jsii_.MemberMethod{JsiiMethod: "resetPipelinesEnabled", GoMethod: "ResetPipelinesEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetPrintingMergeRequestLinkEnabled", GoMethod: "ResetPrintingMergeRequestLinkEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetPublicBuilds", GoMethod: "ResetPublicBuilds"},
			_jsii_.MemberMethod{JsiiMethod: "resetPushRules", GoMethod: "ResetPushRules"},
			_jsii_.MemberMethod{JsiiMethod: "resetRemoveSourceBranchAfterMerge", GoMethod: "ResetRemoveSourceBranchAfterMerge"},
			_jsii_.MemberMethod{JsiiMethod: "resetRepositoryAccessLevel", GoMethod: "ResetRepositoryAccessLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetRepositoryStorage", GoMethod: "ResetRepositoryStorage"},
			_jsii_.MemberMethod{JsiiMethod: "resetRequestAccessEnabled", GoMethod: "ResetRequestAccessEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetRequirementsAccessLevel", GoMethod: "ResetRequirementsAccessLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetResolveOutdatedDiffDiscussions", GoMethod: "ResetResolveOutdatedDiffDiscussions"},
			_jsii_.MemberMethod{JsiiMethod: "resetRestrictUserDefinedVariables", GoMethod: "ResetRestrictUserDefinedVariables"},
			_jsii_.MemberMethod{JsiiMethod: "resetSecurityAndComplianceAccessLevel", GoMethod: "ResetSecurityAndComplianceAccessLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetSharedRunnersEnabled", GoMethod: "ResetSharedRunnersEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetSkipWaitForDefaultBranchProtection", GoMethod: "ResetSkipWaitForDefaultBranchProtection"},
			_jsii_.MemberMethod{JsiiMethod: "resetSnippetsAccessLevel", GoMethod: "ResetSnippetsAccessLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetSnippetsEnabled", GoMethod: "ResetSnippetsEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetSquashCommitTemplate", GoMethod: "ResetSquashCommitTemplate"},
			_jsii_.MemberMethod{JsiiMethod: "resetSquashOption", GoMethod: "ResetSquashOption"},
			_jsii_.MemberMethod{JsiiMethod: "resetSuggestionCommitMessage", GoMethod: "ResetSuggestionCommitMessage"},
			_jsii_.MemberMethod{JsiiMethod: "resetTags", GoMethod: "ResetTags"},
			_jsii_.MemberMethod{JsiiMethod: "resetTemplateName", GoMethod: "ResetTemplateName"},
			_jsii_.MemberMethod{JsiiMethod: "resetTemplateProjectId", GoMethod: "ResetTemplateProjectId"},
			_jsii_.MemberMethod{JsiiMethod: "resetTopics", GoMethod: "ResetTopics"},
			_jsii_.MemberMethod{JsiiMethod: "resetUseCustomTemplate", GoMethod: "ResetUseCustomTemplate"},
			_jsii_.MemberMethod{JsiiMethod: "resetVisibilityLevel", GoMethod: "ResetVisibilityLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetWikiAccessLevel", GoMethod: "ResetWikiAccessLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetWikiEnabled", GoMethod: "ResetWikiEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "resolveOutdatedDiffDiscussions", GoGetter: "ResolveOutdatedDiffDiscussions"},
			_jsii_.MemberProperty{JsiiProperty: "resolveOutdatedDiffDiscussionsInput", GoGetter: "ResolveOutdatedDiffDiscussionsInput"},
			_jsii_.MemberProperty{JsiiProperty: "restrictUserDefinedVariables", GoGetter: "RestrictUserDefinedVariables"},
			_jsii_.MemberProperty{JsiiProperty: "restrictUserDefinedVariablesInput", GoGetter: "RestrictUserDefinedVariablesInput"},
			_jsii_.MemberProperty{JsiiProperty: "runnersToken", GoGetter: "RunnersToken"},
			_jsii_.MemberProperty{JsiiProperty: "securityAndComplianceAccessLevel", GoGetter: "SecurityAndComplianceAccessLevel"},
			_jsii_.MemberProperty{JsiiProperty: "securityAndComplianceAccessLevelInput", GoGetter: "SecurityAndComplianceAccessLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "sharedRunnersEnabled", GoGetter: "SharedRunnersEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "sharedRunnersEnabledInput", GoGetter: "SharedRunnersEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "skipWaitForDefaultBranchProtection", GoGetter: "SkipWaitForDefaultBranchProtection"},
			_jsii_.MemberProperty{JsiiProperty: "skipWaitForDefaultBranchProtectionInput", GoGetter: "SkipWaitForDefaultBranchProtectionInput"},
			_jsii_.MemberProperty{JsiiProperty: "snippetsAccessLevel", GoGetter: "SnippetsAccessLevel"},
			_jsii_.MemberProperty{JsiiProperty: "snippetsAccessLevelInput", GoGetter: "SnippetsAccessLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "snippetsEnabled", GoGetter: "SnippetsEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "snippetsEnabledInput", GoGetter: "SnippetsEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "squashCommitTemplate", GoGetter: "SquashCommitTemplate"},
			_jsii_.MemberProperty{JsiiProperty: "squashCommitTemplateInput", GoGetter: "SquashCommitTemplateInput"},
			_jsii_.MemberProperty{JsiiProperty: "squashOption", GoGetter: "SquashOption"},
			_jsii_.MemberProperty{JsiiProperty: "squashOptionInput", GoGetter: "SquashOptionInput"},
			_jsii_.MemberProperty{JsiiProperty: "sshUrlToRepo", GoGetter: "SshUrlToRepo"},
			_jsii_.MemberProperty{JsiiProperty: "suggestionCommitMessage", GoGetter: "SuggestionCommitMessage"},
			_jsii_.MemberProperty{JsiiProperty: "suggestionCommitMessageInput", GoGetter: "SuggestionCommitMessageInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "tags", GoGetter: "Tags"},
			_jsii_.MemberProperty{JsiiProperty: "tagsInput", GoGetter: "TagsInput"},
			_jsii_.MemberProperty{JsiiProperty: "templateName", GoGetter: "TemplateName"},
			_jsii_.MemberProperty{JsiiProperty: "templateNameInput", GoGetter: "TemplateNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "templateProjectId", GoGetter: "TemplateProjectId"},
			_jsii_.MemberProperty{JsiiProperty: "templateProjectIdInput", GoGetter: "TemplateProjectIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "topics", GoGetter: "Topics"},
			_jsii_.MemberProperty{JsiiProperty: "topicsInput", GoGetter: "TopicsInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "useCustomTemplate", GoGetter: "UseCustomTemplate"},
			_jsii_.MemberProperty{JsiiProperty: "useCustomTemplateInput", GoGetter: "UseCustomTemplateInput"},
			_jsii_.MemberProperty{JsiiProperty: "visibilityLevel", GoGetter: "VisibilityLevel"},
			_jsii_.MemberProperty{JsiiProperty: "visibilityLevelInput", GoGetter: "VisibilityLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "webUrl", GoGetter: "WebUrl"},
			_jsii_.MemberProperty{JsiiProperty: "wikiAccessLevel", GoGetter: "WikiAccessLevel"},
			_jsii_.MemberProperty{JsiiProperty: "wikiAccessLevelInput", GoGetter: "WikiAccessLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "wikiEnabled", GoGetter: "WikiEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "wikiEnabledInput", GoGetter: "WikiEnabledInput"},
		},
		func() interface{} {
			j := jsiiProxy_Project{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-gitlab.project.ProjectConfig",
		reflect.TypeOf((*ProjectConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-gitlab.project.ProjectContainerExpirationPolicy",
		reflect.TypeOf((*ProjectContainerExpirationPolicy)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-gitlab.project.ProjectContainerExpirationPolicyOutputReference",
		reflect.TypeOf((*ProjectContainerExpirationPolicyOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "cadence", GoGetter: "Cadence"},
			_jsii_.MemberProperty{JsiiProperty: "cadenceInput", GoGetter: "CadenceInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "enabled", GoGetter: "Enabled"},
			_jsii_.MemberProperty{JsiiProperty: "enabledInput", GoGetter: "EnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "keepN", GoGetter: "KeepN"},
			_jsii_.MemberProperty{JsiiProperty: "keepNInput", GoGetter: "KeepNInput"},
			_jsii_.MemberProperty{JsiiProperty: "nameRegexDelete", GoGetter: "NameRegexDelete"},
			_jsii_.MemberProperty{JsiiProperty: "nameRegexDeleteInput", GoGetter: "NameRegexDeleteInput"},
			_jsii_.MemberProperty{JsiiProperty: "nameRegexKeep", GoGetter: "NameRegexKeep"},
			_jsii_.MemberProperty{JsiiProperty: "nameRegexKeepInput", GoGetter: "NameRegexKeepInput"},
			_jsii_.MemberProperty{JsiiProperty: "nextRunAt", GoGetter: "NextRunAt"},
			_jsii_.MemberProperty{JsiiProperty: "olderThan", GoGetter: "OlderThan"},
			_jsii_.MemberProperty{JsiiProperty: "olderThanInput", GoGetter: "OlderThanInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetCadence", GoMethod: "ResetCadence"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnabled", GoMethod: "ResetEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetKeepN", GoMethod: "ResetKeepN"},
			_jsii_.MemberMethod{JsiiMethod: "resetNameRegexDelete", GoMethod: "ResetNameRegexDelete"},
			_jsii_.MemberMethod{JsiiMethod: "resetNameRegexKeep", GoMethod: "ResetNameRegexKeep"},
			_jsii_.MemberMethod{JsiiMethod: "resetOlderThan", GoMethod: "ResetOlderThan"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ProjectContainerExpirationPolicyOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-gitlab.project.ProjectPushRules",
		reflect.TypeOf((*ProjectPushRules)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-gitlab.project.ProjectPushRulesOutputReference",
		reflect.TypeOf((*ProjectPushRulesOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "authorEmailRegex", GoGetter: "AuthorEmailRegex"},
			_jsii_.MemberProperty{JsiiProperty: "authorEmailRegexInput", GoGetter: "AuthorEmailRegexInput"},
			_jsii_.MemberProperty{JsiiProperty: "branchNameRegex", GoGetter: "BranchNameRegex"},
			_jsii_.MemberProperty{JsiiProperty: "branchNameRegexInput", GoGetter: "BranchNameRegexInput"},
			_jsii_.MemberProperty{JsiiProperty: "commitCommitterCheck", GoGetter: "CommitCommitterCheck"},
			_jsii_.MemberProperty{JsiiProperty: "commitCommitterCheckInput", GoGetter: "CommitCommitterCheckInput"},
			_jsii_.MemberProperty{JsiiProperty: "commitMessageNegativeRegex", GoGetter: "CommitMessageNegativeRegex"},
			_jsii_.MemberProperty{JsiiProperty: "commitMessageNegativeRegexInput", GoGetter: "CommitMessageNegativeRegexInput"},
			_jsii_.MemberProperty{JsiiProperty: "commitMessageRegex", GoGetter: "CommitMessageRegex"},
			_jsii_.MemberProperty{JsiiProperty: "commitMessageRegexInput", GoGetter: "CommitMessageRegexInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "denyDeleteTag", GoGetter: "DenyDeleteTag"},
			_jsii_.MemberProperty{JsiiProperty: "denyDeleteTagInput", GoGetter: "DenyDeleteTagInput"},
			_jsii_.MemberProperty{JsiiProperty: "fileNameRegex", GoGetter: "FileNameRegex"},
			_jsii_.MemberProperty{JsiiProperty: "fileNameRegexInput", GoGetter: "FileNameRegexInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "maxFileSize", GoGetter: "MaxFileSize"},
			_jsii_.MemberProperty{JsiiProperty: "maxFileSizeInput", GoGetter: "MaxFileSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "memberCheck", GoGetter: "MemberCheck"},
			_jsii_.MemberProperty{JsiiProperty: "memberCheckInput", GoGetter: "MemberCheckInput"},
			_jsii_.MemberProperty{JsiiProperty: "preventSecrets", GoGetter: "PreventSecrets"},
			_jsii_.MemberProperty{JsiiProperty: "preventSecretsInput", GoGetter: "PreventSecretsInput"},
			_jsii_.MemberProperty{JsiiProperty: "rejectUnsignedCommits", GoGetter: "RejectUnsignedCommits"},
			_jsii_.MemberProperty{JsiiProperty: "rejectUnsignedCommitsInput", GoGetter: "RejectUnsignedCommitsInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAuthorEmailRegex", GoMethod: "ResetAuthorEmailRegex"},
			_jsii_.MemberMethod{JsiiMethod: "resetBranchNameRegex", GoMethod: "ResetBranchNameRegex"},
			_jsii_.MemberMethod{JsiiMethod: "resetCommitCommitterCheck", GoMethod: "ResetCommitCommitterCheck"},
			_jsii_.MemberMethod{JsiiMethod: "resetCommitMessageNegativeRegex", GoMethod: "ResetCommitMessageNegativeRegex"},
			_jsii_.MemberMethod{JsiiMethod: "resetCommitMessageRegex", GoMethod: "ResetCommitMessageRegex"},
			_jsii_.MemberMethod{JsiiMethod: "resetDenyDeleteTag", GoMethod: "ResetDenyDeleteTag"},
			_jsii_.MemberMethod{JsiiMethod: "resetFileNameRegex", GoMethod: "ResetFileNameRegex"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxFileSize", GoMethod: "ResetMaxFileSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetMemberCheck", GoMethod: "ResetMemberCheck"},
			_jsii_.MemberMethod{JsiiMethod: "resetPreventSecrets", GoMethod: "ResetPreventSecrets"},
			_jsii_.MemberMethod{JsiiMethod: "resetRejectUnsignedCommits", GoMethod: "ResetRejectUnsignedCommits"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ProjectPushRulesOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
